[2019-02-22 10:33:31] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:14) - 错误信息: class java.lang.NullPointerException null
	at com.apitest.component.EnvComponent.getEnviroment(EnvComponent.java:23)
	at com.apitest.rest.RestRequest.getCookie(RestRequest.java:116)
	at com.apitest.rest.RestRequest.<clinit>(RestRequest.java:44)

[2019-02-22 10:33:31] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:15) - 线程名: main,线程id: 1,线程状态: RUNNABLE
[2019-02-22 10:35:42] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:14) - 错误信息: class java.lang.NullPointerException null
	at com.apitest.component.EnvComponent.getEnviroment(EnvComponent.java:23)
	at com.apitest.rest.RestRequest.getCookie(RestRequest.java:116)
	at com.apitest.rest.RestRequest.<clinit>(RestRequest.java:44)

[2019-02-22 10:35:42] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:15) - 线程名: main,线程id: 1,线程状态: RUNNABLE
[2019-02-22 10:37:13] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:14) - 错误信息: class java.lang.NullPointerException null
	at com.apitest.component.EnvComponent.getEnviroment(EnvComponent.java:23)
	at com.apitest.rest.RestRequest.getCookie(RestRequest.java:116)
	at com.apitest.rest.RestRequest.<clinit>(RestRequest.java:44)

[2019-02-22 10:37:13] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:15) - 线程名: main,线程id: 1,线程状态: RUNNABLE
[2019-02-22 10:37:36] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:14) - 错误信息: class java.lang.NullPointerException null
	at com.apitest.component.EnvComponent.getEnviroment(EnvComponent.java:23)
	at com.apitest.rest.RestRequest.getCookie(RestRequest.java:116)
	at com.apitest.rest.RestRequest.<clinit>(RestRequest.java:44)

[2019-02-22 10:37:36] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:15) - 线程名: main,线程id: 1,线程状态: RUNNABLE
[2019-02-22 10:38:49] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:14) - 错误信息: class java.lang.NullPointerException null
	at com.apitest.component.EnvComponent.getEnviroment(EnvComponent.java:23)
	at com.apitest.rest.RestRequest.getCookie(RestRequest.java:116)
	at com.apitest.rest.RestRequest.<clinit>(RestRequest.java:44)

[2019-02-22 10:38:49] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:15) - 线程名: main,线程id: 1,线程状态: RUNNABLE
[2019-02-22 10:54:00] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:14) - 错误信息: class java.lang.NullPointerException null
	at com.apitest.component.EnvComponent.getEnviroment(EnvComponent.java:23)
	at com.apitest.rest.RestRequest.getCookie(RestRequest.java:118)
	at com.apitest.rest.RestRequest.<clinit>(RestRequest.java:38)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

[2019-02-22 10:54:00] - [main] - com.apitest.util.ExceptionUtil.<init>(ExceptionUtil.java:15) - 线程名: main,线程id: 1,线程状态: RUNNABLE
